// export const API_URL = "http://api.o-rama.store";
// export const API_URL = "https://us-central1-o-rama2.cloudfunctions.net/api";
//export const API_URL = "http://35.247.212.164";
export const API_URL = "https://us-central1-o-rama2.cloudfunctions.net/api";
export const FB_APP_ACCESS_TOKEN = "410996659284985|7Xr3cNTZce1h1m2iJFEQQdBXpYg";
export const CHAT = 'orama'
export const LOG_REDUX = false
export const LOG_NOTIFICATION = false
export const SENDER_ID = '227774758672'